baseURL = 'https://hugotest-9js.pages.dev/'
languageCode = 'en-us'
title = 'conservative cybernetics'
theme= 'hugo-PaperMod'
[params]
  stylesheet = "/layouts/css/main.css"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
